
project_id = "lielkkbyfruhtckbinaq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
tenant_id = "realtime-dev"

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54327
external_url = "http://localhost:3000"
additional_redirect_urls = ["https://mentor-ai-genesis.lovable.app"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[edge-runtime]
enabled = true
port = 54328

[[edge-runtime.functions]]
name = "gemini-chat"
verify_jwt = true

[[edge-runtime.functions]]
name = "process-pdf"
verify_jwt = true
