// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lielkkbyfruhtckbinaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpZWxra2J5ZnJ1aHRja2JpbmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTI3NDYsImV4cCI6MjA2NDk2ODc0Nn0.ZWAs1SkC3n_9c0SvqoJBhSvC0lmyqKOT_U6k0L-8N24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);